development:
	npm install
	NODE_ENV=development npm start

production:
	npm install
	NODE_ENV=production npm run build
	NODE_ENV=production npm run serve

test:
	npm install
	npm test

default: development