version: '2'
services:
  server:
    container_name: server
    restart: unless-stopped
    build: server
    environment:
      - REDIS_URL=redis://cache
      - MONGO_URL=mongodb://mongo:27017/newdock
      - EXPRESS_PORT=4000
      - COINMARKETCAP_APIKEY=$COINMARKETCAP_APIKEY
    ports:
      - '4000:4000'
    links:
      - mongo
      - redis
  mongo:
    container_name: mongo
    restart: unless-stopped
    image: mongo
    ports:
      - '27017:27017'
  redis:
    image: redis
    container_name: cache
    expose:
      - 6379
