version: '2'
services:
  mongo:
    container_name: mongo
    restart: unless-stopped
    image: mongo
    ports:
      - '27017:27017'
  redis:
    image: redis
    container_name: cache
    expose:
      - 6379
  api-server:
    container_name: api-server
    restart: always
    build:
      context: api-server
      dockerfile: Dockerfile-production
    environment:
      - REDIS_URL=redis://cache
      - MONGO_URL=mongodb://mongo:27017/newdock
      - API_PORT=4000
      - COINMARKETCAP_APIKEY=$COINMARKETCAP_APIKEY
    volumes:
      - './api-server:/app/api-server'
    ports:
      - '4000:4000'
    links:
      - mongo
      - redis
  web-server:
    container_name: web-server
    restart: always
    environment:
      - WEBSERVER_PORT=80
    build:
      context: web-server
      dockerfile: Dockerfile-production
    ports:
      - '80:80'

