version: '2'
services:
  app:
    container_name: app
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - REDIS_URL=redis://cache
      - MONGO_URL=mongodb://mongo:27017/newdock
      - EXPRESS_PORT=4000
      - COINMARKETAPP_APIKEY=$COINMARKETAPP_APIKEY
    ports:
      - '4000:4000'
    links:
      - mongo
      - redis
  mongo:
    container_name: mongo
    restart: unless-stopped
    image: mongo
    ports:
      - '27017:27017'
  redis:
    image: redis
    container_name: cache
    expose:
      - 6379
